### ISSUE TITLE
[BUGS] 问题

### ISSUE THREAD

**Issue by Hikari0964** [Loyisa/ShadowBan#11]
## Information

Your Server Version: 1.8.8

ProtocolLib Version: 4.7.0

ShadowBan Version: 1.1.3

## Other Infomation

What bugs you found: 
1.shadowban unban这个命令在什么时候都显示正在移出玩家

但是数据库中并没有ban的玩家

2.shadowban最新构建会给所有人加上挖/放置方块回弹，但是不会一拳超人

**Comment by re-ovo** [comment]
2. 好像是因为少了个`!`

**Comment by re-ovo** [comment]
发布了修复，试试吧

**Comment by Hikari0964** [comment]
ok谢谢RE
